spring:
  datasource:
    url: jdbc:mysql://localhost:3306/food?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: Miku
    password: 39
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8081